// Module included in the following assemblies:
//
// * machine_management/creating-infrastructure-machinesets.adoc
// * machine_management/creating_machinesets/creating-machineset-bare-metal.adoc

ifeval::["{context}" == "creating-infrastructure-machinesets"]
:infra:
endif::[]

:_mod-docs-content-type: REFERENCE
[id="machineset-yaml-vsphere_{context}"]
= Sample YAML for a compute machine set custom resource on bare metal

[role="_abstract"]
Define and apply a compute machine set on bare metal to automate node provisioning. The sample bare metal YAML defines a compute machine set that runs on bare metal and creates nodes that are labeled with
ifndef::infra[`node-role.kubernetes.io/<role>: ""`.]
ifdef::infra[`node-role.kubernetes.io/infra: ""`.]

In the sample, `<infrastructure_id>` is the infrastructure ID label that is based on the cluster ID that you set when you provisioned the cluster, and
ifndef::infra[`<role>`]
ifdef::infra[`<infra>`]
is the node label to add.

[source,yaml]
----
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: <infrastructure_id>
ifndef::infra[]
  name: <infrastructure_id>-<role>
endif::infra[]
ifdef::infra[]
  name: <infrastructure_id>-infra
endif::infra[]
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <infrastructure_id>
ifndef::infra[]
      machine.openshift.io/cluster-api-machineset: <infrastructure_id>-<role>
endif::infra[]
ifdef::infra[]
      machine.openshift.io/cluster-api-machineset: <infrastructure_id>-infra
endif::infra[]
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: <infrastructure_id>
ifndef::infra[]
        machine.openshift.io/cluster-api-machine-role: <role>
        machine.openshift.io/cluster-api-machine-type: <role>
        machine.openshift.io/cluster-api-machineset: <infrastructure_id>-<role>
endif::infra[]
ifdef::infra[]
        machine.openshift.io/cluster-api-machine-role: <infra>
        machine.openshift.io/cluster-api-machine-type: <infra>
        machine.openshift.io/cluster-api-machineset: <infrastructure_id>-infra
endif::infra[]
    spec:
      metadata:
        creationTimestamp: null
        labels:
ifndef::infra[]
          node-role.kubernetes.io/<role>: ""
endif::infra[]
ifdef::infra[]
          node-role.kubernetes.io/infra: ""
      taints:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
endif::infra[]
      providerSpec:
        value:
          apiVersion: baremetal.cluster.k8s.io/v1alpha1
          hostSelector: {}
          image:
            checksum: <image_checksum>
            url: <image_url>
          kind: BareMetalMachineProviderSpec
          metadata:
            creationTimestamp: null
          userData:
            name: worker-user-data-managed
----

where:

`<infrastructure_id>`:: Specifies the infrastructure ID that is based on the cluster ID that you set when you provisioned the cluster. If you have the  {oc-first} installed, you can obtain the infrastructure ID by running the following command:
+
[source,terminal]
----
$ oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster
----
ifndef::infra[]
`<infrastructure_id>-<role>`:: Specifies the infrastructure ID and node label.
`<role>`:: Specifies the node label to add.
[NOTE]
====
`<image.checksum>`:: Specifies the image checksum in the following format:  `\http://172.22.0.3:6181/images/rhcos-<version>.<architecture>.qcow2.<md5sum>`.

`<image.url>`:: Specifies the image URL in the following format: `\http://172.22.0.3:6181/images/rhcos-<version>.<architecture>.qcow2`.

====
endif::infra[]
ifdef::infra[]
`<role>`:: Specifies the node label to add.
`<infrastructure_id>-infra`:: Specifies the infrastructure ID and `infra` node label.
`node-role.kubernetes.io/<role>`:: Specifies the node label to add.
`node-role.kubernetes.io/infra`:: Specifies the `infra` node label to add.
[NOTE]
====
The value of the `spec.template.spec.metadata.taints` parameter specifies a taint to prevent user workloads from being scheduled on infra nodes.
====
endif::infra[]

ifeval::["{context}" == "creating-infrastructure-machinesets"]
:!infra:
endif::[]
ifeval::["{context}" == "cluster-tasks"]
:!infra:
endif::[]
